export const teamTacticalEventDefinitions = [
  { stableId: 'global-tactical-build-up-from-goalkeeper-controlled-exit', name: 'Build-up from goalkeeper controlled exit', description: 'What counts? From goalkeeper restart/build-up, our team reaches the middle third with controlled possession. This is a simplified coaching observation, not an Opta build-up attack.', matchPhase: 'IN_POSSESSION', category: 'GOALKEEPING', subcategory: 'Team tactical - Playing out', matchDayGroup: 'GOALKEEPING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'GOALKEEPER'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-build-up-from-goalkeeper-possession-lost', name: 'Build-up from goalkeeper possession lost', description: 'What counts? From goalkeeper restart/build-up, possession is lost before controlled possession reaches the middle third.', matchPhase: 'IN_POSSESSION', category: 'GOALKEEPING', subcategory: 'Team tactical - Playing out', matchDayGroup: 'GOALKEEPING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'GOALKEEPER'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-build-up-from-goalkeeper-ball-out', name: 'Build-up from goalkeeper ball out', description: 'What counts? From goalkeeper restart/build-up, the ball goes out of play before controlled possession reaches the middle third.', matchPhase: 'IN_POSSESSION', category: 'GOALKEEPING', subcategory: 'Team tactical - Playing out', matchDayGroup: 'GOALKEEPING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'GOALKEEPER'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-escape-opposition-press-retained', name: 'Escape opposition press retained', description: 'What counts? Under an active opposition press, our team plays beyond the first pressing unit and keeps controlled possession.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Playing out', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-escape-opposition-press-unsuccessful', name: 'Escape opposition press unsuccessful', description: 'What counts? Under an active opposition press, our team tries to play through/around/over it but loses possession, plays out, or cannot progress beyond the pressing unit.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Playing out', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-break-opposition-midfield-line-completed', name: 'Break opposition midfield line completed', description: 'What counts? The ball is played or carried beyond the opposition midfield unit and our team has the next controlled action. Optional detail: through, around or over.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Progression', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-break-opposition-midfield-line-incomplete', name: 'Break opposition midfield line incomplete', description: 'What counts? The intended line-break action through, around or over the opposition midfield unit does not result in our next controlled action.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Progression', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-ball-behind-defensive-line-teammate-receives', name: 'Ball behind defensive line teammate receives', description: 'What counts? A deliberate ball behind the opposition defensive line is received or controlled by our teammate.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Progression', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'FORWARD', 'WIDE_PLAYER'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-ball-behind-defensive-line-opponent-wins', name: 'Ball behind defensive line opponent wins', description: 'What counts? A deliberate ball behind the opposition defensive line is won or controlled by the opponent.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Progression', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'FORWARD', 'WIDE_PLAYER'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-ball-behind-defensive-line-offside', name: 'Ball behind defensive line offside', description: 'What counts? A deliberate ball behind the opposition defensive line results in our player being given offside.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Progression', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'FORWARD', 'WIDE_PLAYER'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-ball-behind-defensive-line-out', name: 'Ball behind defensive line out', description: 'What counts? A deliberate ball behind the opposition defensive line runs directly out of play before anyone controls it.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Progression', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'FORWARD', 'WIDE_PLAYER'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-final-third-entry-by-pass', name: 'Final-third entry by pass', description: 'What counts? Our first entry into the attacking third in a possession is by pass. Optional route detail: left, centre or right. Simplified coaching observation, not FIFA EFI compatible.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Final-third entries', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], requiresLocation: true, enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-final-third-entry-by-carry', name: 'Final-third entry by carry', description: 'What counts? Our first entry into the attacking third in a possession is by carrying the ball. Optional route detail: left, centre or right. Simplified coaching observation, not FIFA EFI compatible.', matchPhase: 'IN_POSSESSION', category: 'DRIBBLING_1V1', subcategory: 'Team tactical - Final-third entries', matchDayGroup: 'POSSESSION', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], requiresLocation: true, enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-penalty-area-entry-pass-controlled', name: 'Penalty-area entry pass controlled', description: 'What counts? A pass enters the opposition penalty area and our team has the next controlled touch or usable possession.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Penalty-area entries', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], requiresLocation: true, enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-penalty-area-entry-pass-unsuccessful', name: 'Penalty-area entry pass unsuccessful', description: 'What counts? A pass intended to enter the opposition penalty area does not produce our next controlled touch or usable possession.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Penalty-area entries', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], requiresLocation: true, enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-penalty-area-entry-carry-controlled', name: 'Penalty-area entry carry controlled', description: 'What counts? A carry enters the opposition penalty area and our team retains controlled possession.', matchPhase: 'IN_POSSESSION', category: 'DRIBBLING_1V1', subcategory: 'Team tactical - Penalty-area entries', matchDayGroup: 'POSSESSION', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], requiresLocation: true, enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-penalty-area-entry-carry-unsuccessful', name: 'Penalty-area entry carry unsuccessful', description: 'What counts? A carry intended to enter or continue in the opposition penalty area breaks down before controlled possession is retained.', matchPhase: 'IN_POSSESSION', category: 'DRIBBLING_1V1', subcategory: 'Team tactical - Penalty-area entries', matchDayGroup: 'POSSESSION', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], requiresLocation: true, enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-penalty-area-entry-cross-controlled', name: 'Penalty-area entry cross controlled', description: 'What counts? A cross enters the opposition penalty area and reaches a teammate or produces our next controlled touch.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Penalty-area entries', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'WIDE_PLAYER', 'FORWARD'], requiresLocation: true, enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-penalty-area-entry-cross-unsuccessful', name: 'Penalty-area entry cross unsuccessful', description: 'What counts? A cross intended for the opposition penalty area does not reach a teammate or our next controlled touch.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Penalty-area entries', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'WIDE_PLAYER', 'FORWARD'], requiresLocation: true, enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-switch-of-play-completed', name: 'Switch of play completed', description: 'What counts? The ball moves from one side/wide channel to the opposite side and reaches a teammate or controlled target area.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Wide attacks', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-switch-of-play-incomplete', name: 'Switch of play incomplete', description: 'What counts? The intended switch from one side/wide channel to the opposite side does not reach a teammate or controlled target area.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Wide attacks', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-cutback-reaches-teammate', name: 'Cutback reaches teammate', description: 'What counts? A pass pulled back from the byline or wide channel reaches a teammate in a central scoring area.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Wide attacks', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'WIDE_PLAYER', 'FORWARD'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-cutback-intercepted', name: 'Cutback intercepted', description: 'What counts? A cutback from the byline or wide channel is cut out by an opponent before reaching the intended central area.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Wide attacks', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'WIDE_PLAYER', 'FORWARD'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-cutback-out', name: 'Cutback out', description: 'What counts? A cutback from the byline or wide channel goes directly out of play.', matchPhase: 'IN_POSSESSION', category: 'PASSING', subcategory: 'Team tactical - Wide attacks', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL', 'WIDE_PLAYER', 'FORWARD'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-press-triggered-regain', name: 'Press triggered regain', description: 'What counts? Our press directly causes us to regain possession. Do not count all regains as pressing success.', matchPhase: 'OUT_OF_POSSESSION', category: 'DEFENDING', subcategory: 'Team tactical - Pressing', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-press-triggered-force-long-ball', name: 'Press triggered force long ball', description: 'What counts? Our press forces the opponent into an uncontrolled or lower-quality long ball. A later regain can be recorded separately if it happens.', matchPhase: 'OUT_OF_POSSESSION', category: 'DEFENDING', subcategory: 'Team tactical - Pressing', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-press-triggered-force-backwards', name: 'Press triggered force backwards', description: 'What counts? Our press forces the opponent to play backwards or away from goal without us necessarily regaining possession.', matchPhase: 'OUT_OF_POSSESSION', category: 'DEFENDING', subcategory: 'Team tactical - Pressing', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-press-triggered-opponent-escapes', name: 'Press triggered opponent escapes', description: 'What counts? The opponent plays beyond our press and keeps controlled possession.', matchPhase: 'OUT_OF_POSSESSION', category: 'DEFENDING', subcategory: 'Team tactical - Pressing', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-counter-press-regain', name: 'Counter-press regain', description: 'What counts? We recover controlled possession within 5 seconds of losing it. The 5-second rule is part of this observation identity.', matchPhase: 'TRANSITION', category: 'DEFENDING', subcategory: 'Team tactical - Transition', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attack-following-regain-box-entry', name: 'Attack following regain box entry', description: 'What counts? After an explicitly observed regain, the following attack reaches the opposition box. Use only when the relationship is clear from live observation.', matchPhase: 'TRANSITION', category: 'SHOOTING', subcategory: 'Team tactical - Counter-attacking', matchDayGroup: 'GOALS_OUTCOMES', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attack-following-regain-shot', name: 'Attack following regain shot', description: 'What counts? After an explicitly observed regain, the following attack produces a shot. Use only when the relationship is clear from live observation.', matchPhase: 'TRANSITION', category: 'SHOOTING', subcategory: 'Team tactical - Counter-attacking', matchDayGroup: 'GOALS_OUTCOMES', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attack-following-regain-goal', name: 'Attack following regain goal', description: 'What counts? After an explicitly observed regain, the following attack produces a goal. Use only when the relationship is clear from live observation.', matchPhase: 'TRANSITION', category: 'SHOOTING', subcategory: 'Team tactical - Counter-attacking', matchDayGroup: 'GOALS_OUTCOMES', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attack-following-regain-possession-lost', name: 'Attack following regain possession lost', description: 'What counts? After an explicitly observed regain, the following attack breaks down before box entry or shot.', matchPhase: 'TRANSITION', category: 'PASSING', subcategory: 'Team tactical - Counter-attacking', matchDayGroup: 'POSSESSION', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-opposition-attack-following-our-loss-stopped', name: 'Opposition attack following our loss stopped', description: 'What counts? Immediately after our clear loss, we stop the opponent attack before it reaches our box or produces a shot.', matchPhase: 'TRANSITION', category: 'DEFENDING', subcategory: 'Team tactical - Defensive transition', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-opposition-attack-following-our-loss-delayed', name: 'Opposition attack following our loss delayed', description: 'What counts? Immediately after our clear loss, we slow the opponent attack enough for defensive recovery, without clear box entry or shot conceded yet.', matchPhase: 'TRANSITION', category: 'DEFENDING', subcategory: 'Team tactical - Defensive transition', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-opposition-attack-following-our-loss-box-entry-conceded', name: 'Opposition attack following our loss box entry conceded', description: 'What counts? Immediately after our clear loss, the opponent attack enters our penalty area.', matchPhase: 'TRANSITION', category: 'DEFENDING', subcategory: 'Team tactical - Defensive transition', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-opposition-attack-following-our-loss-shot-conceded', name: 'Opposition attack following our loss shot conceded', description: 'What counts? Immediately after our clear loss, the opponent attack produces a shot.', matchPhase: 'TRANSITION', category: 'DEFENDING', subcategory: 'Team tactical - Defensive transition', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-second-ball-won', name: 'Second ball won', description: 'What counts? The next contested ball after an aerial challenge, clearance or direct ball is won by our team before either side has clear control. Optional zone: defensive, middle or attacking third.', matchPhase: 'OUT_OF_POSSESSION', category: 'DEFENDING', subcategory: 'Team tactical - Duels', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-second-ball-lost', name: 'Second ball lost', description: 'What counts? The next contested ball after an aerial challenge, clearance or direct ball is won by the opponent before either side has clear control. Optional zone: defensive, middle or attacking third.', matchPhase: 'OUT_OF_POSSESSION', category: 'DEFENDING', subcategory: 'Team tactical - Duels', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-opposition-central-penetration-prevented', name: 'Opposition central penetration prevented', description: 'What counts? The opponent attempts to progress through the central channel but we stop or redirect the attack before central penetration is completed.', matchPhase: 'OUT_OF_POSSESSION', category: 'DEFENDING', subcategory: 'Team tactical - Defending', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-opposition-central-penetration-completed', name: 'Opposition central penetration completed', description: 'What counts? The opponent progresses through the central channel beyond our midfield or defensive screen, optionally leading to box entry or shot.', matchPhase: 'OUT_OF_POSSESSION', category: 'DEFENDING', subcategory: 'Team tactical - Defending', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attacking-corner-routine', name: 'Attacking corner routine', description: 'What counts? Our planned or repeatable attacking corner routine is delivered. Optional detail records delivery zone.', matchPhase: 'SET_PIECES', category: 'OTHER', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'CUSTOM_OTHER', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attacking-free-kick-routine', name: 'Attacking free-kick routine', description: 'What counts? Our planned or repeatable attacking free-kick routine is delivered. Optional detail records delivery zone.', matchPhase: 'SET_PIECES', category: 'OTHER', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'CUSTOM_OTHER', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attacking-set-piece-first-contact-won', name: 'Attacking set-piece first contact won', description: 'What counts? From our corner or attacking free kick, our team makes the first meaningful contact after delivery.', matchPhase: 'SET_PIECES', category: 'OTHER', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'CUSTOM_OTHER', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attacking-set-piece-first-contact-lost', name: 'Attacking set-piece first contact lost', description: 'What counts? From our corner or attacking free kick, the opposition makes the first meaningful contact after delivery.', matchPhase: 'SET_PIECES', category: 'OTHER', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'CUSTOM_OTHER', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-attacking-set-piece-shot', name: 'Attacking set-piece shot', description: 'What counts? Our corner or attacking free-kick routine produces a shot before the set-piece phase has clearly ended.', matchPhase: 'SET_PIECES', category: 'SHOOTING', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'SHOOTING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-defending-corner-or-free-kick-first-contact-won', name: 'Defending corner or free kick first contact won', description: 'What counts? From an opposition corner or free kick, our team makes the first meaningful contact after delivery. Optional detail records zone.', matchPhase: 'SET_PIECES', category: 'DEFENDING', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-defending-corner-or-free-kick-first-contact-lost', name: 'Defending corner or free kick first contact lost', description: 'What counts? From an opposition corner or free kick, the opposition makes the first meaningful contact after delivery. Optional detail records zone.', matchPhase: 'SET_PIECES', category: 'DEFENDING', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-defending-set-piece-second-ball-won', name: 'Defending set-piece second ball won', description: 'What counts? After the first contact from an opposition set piece, our team wins the next loose or contested ball.', matchPhase: 'SET_PIECES', category: 'DEFENDING', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-defending-set-piece-second-ball-lost', name: 'Defending set-piece second ball lost', description: 'What counts? After the first contact from an opposition set piece, the opposition wins the next loose or contested ball.', matchPhase: 'SET_PIECES', category: 'DEFENDING', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-defending-set-piece-shot-conceded', name: 'Defending set-piece shot conceded', description: 'What counts? An opposition corner or free-kick routine produces a shot before the set-piece phase has clearly ended.', matchPhase: 'SET_PIECES', category: 'DEFENDING', subcategory: 'Team tactical - Set pieces', matchDayGroup: 'DEFENDING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-our-throw-in-possession-retained', name: 'Our throw-in possession retained', description: 'What counts? From our throw-in, we retain controlled possession after the receiving action or next deliberate team action within 5 seconds.', matchPhase: 'SET_PIECES', category: 'PASSING', subcategory: 'Team tactical - Throw-ins', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
  { stableId: 'global-tactical-our-throw-in-possession-lost', name: 'Our throw-in possession lost', description: 'What counts? From our throw-in, the opposition controls the ball or the ball goes out before we complete the receiving action or next deliberate team action within 5 seconds.', matchPhase: 'SET_PIECES', category: 'PASSING', subcategory: 'Team tactical - Throw-ins', matchDayGroup: 'PASSING', agePhases: ['YOUTH', 'ADULT'], fourCorner: 'TACTICAL', positionRelevance: ['ALL'], enabledByDefault: false, benchmarkable: false },
]

export const tacticalPresetStandardPrerequisiteDefinitions = [
  {
    stableId: 'global-standard-ball-recovery',
    name: 'Ball recovery',
    description: 'What counts? A player establishes controlled possession after a turnover or loose ball. Do not count this as an interception unless they moved into an opponent pass.',
    matchPhase: 'TRANSITION',
    category: 'DEFENDING',
    subcategory: 'Regains',
    matchDayGroup: 'DEFENDING',
    agePhases: ['FOUNDATION', 'YOUTH', 'ADULT'],
    fourCorner: 'TACTICAL',
    positionRelevance: ['ALL'],
    requiresLocation: false,
    enabledByDefault: false,
    benchmarkable: true,
  },
]

export const tacticalPresets = [
  { key: 'playing-out', label: 'Playing out', description: 'Track controlled exits, escaping pressure and breaking the midfield line.', eventNames: ['Build-up from goalkeeper controlled exit', 'Build-up from goalkeeper possession lost', 'Escape opposition press retained', 'Escape opposition press unsuccessful'] },
  { key: 'pressing', label: 'Pressing', description: 'Track what the press causes without labelling every regain as a pressing success.', eventNames: ['Press triggered regain', 'Press triggered force long ball', 'Press triggered opponent escapes', 'Counter-press regain'] },
  { key: 'counter-attacking', label: 'Counter-attacking', description: 'Track whether regains become dangerous attacks.', eventNames: ['Ball recovery', 'Attack following regain box entry', 'Attack following regain shot', 'Attack following regain possession lost'] },
  { key: 'wide-attacks', label: 'Wide attacks', description: 'Track wide entries, switches and cutbacks.', eventNames: ['Final-third entry by pass', 'Final-third entry by carry', 'Switch of play completed', 'Cutback reaches teammate'] },
  { key: 'defending-box', label: 'Defending the box', description: 'Track box protection, second balls and central penetration.', eventNames: ['Second ball won', 'Second ball lost', 'Opposition central penetration prevented', 'Opposition central penetration completed'] },
  { key: 'set-pieces', label: 'Set pieces', description: 'Track repeatable attacking and defending set-piece outcomes.', eventNames: ['Attacking corner routine', 'Attacking set-piece first contact won', 'Defending corner or free kick first contact won', 'Our throw-in possession retained'] },
]

const eventDefinitionSynonyms = {
  completed: 'complete',
  successful: 'complete',
  failed: 'incomplete',
  unsuccessful: 'incomplete',
  accurate: 'target',
  dribble: '1v1',
  dribbling: '1v1',
}

export const normalizeEventDefinitionName = (name) =>
  name
    .toLowerCase()
    .replace(/one\s+v\s+one/g, '1v1')
    .replace(/1\s*v\s*1/g, '1v1')
    .replace(/on\s+target/g, 'target')
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .map((token) => token.trim())
    .filter(Boolean)
    .map((token) => eventDefinitionSynonyms[token] ?? token)
    .map((token) => (token.length > 3 && token.endsWith('s') ? token.slice(0, -1) : token))
    .sort()
    .join(' ')

export const createEventDefinitionSlug = (name) => {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

  return slug || 'event'
}

export function getCanonicalTacticalEventDefinition(definition) {
  return {
    name: definition.name,
    description: definition.description,
    scope: 'GLOBAL',
    clubId: null,
    legacyEventType: null,
    slug: createEventDefinitionSlug(definition.name),
    normalizedName: normalizeEventDefinitionName(definition.name),
    matchPhase: definition.matchPhase,
    category: definition.category,
    subcategory: definition.subcategory,
    matchDayGroup: definition.matchDayGroup,
    agePhases: definition.agePhases,
    fourCorner: definition.fourCorner,
    positionRelevance: definition.positionRelevance,
    enabledByDefault: definition.enabledByDefault ?? false,
    benchmarkable: definition.benchmarkable ?? false,
    requiresLocation: definition.requiresLocation ?? false,
    isActive: definition.isActive ?? true,
    archivedAt: definition.archivedAt ?? null,
  }
}

export function getCanonicalStandardPrerequisiteEventDefinition(definition) {
  return {
    name: definition.name,
    description: definition.description,
    scope: 'GLOBAL',
    clubId: null,
    legacyEventType: null,
    slug: createEventDefinitionSlug(definition.name),
    normalizedName: normalizeEventDefinitionName(definition.name),
    matchPhase: definition.matchPhase,
    category: definition.category,
    subcategory: definition.subcategory,
    matchDayGroup: definition.matchDayGroup,
    agePhases: definition.agePhases,
    fourCorner: definition.fourCorner,
    positionRelevance: definition.positionRelevance,
    enabledByDefault: definition.enabledByDefault ?? false,
    benchmarkable: definition.benchmarkable ?? true,
    requiresLocation: definition.requiresLocation ?? false,
    isActive: definition.isActive ?? true,
    archivedAt: definition.archivedAt ?? null,
  }
}
